name: Native C++/Python - gcc,OpenMPI

on:
  push:
    branches:
      - main
      - 0.**
  pull_request:
    branches: 
      - main
      - 0.**

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends --no-install-suggests g++ python3 python3-dev python3-pip maven libnuma-dev libc-dev python3-venv python3-numpy openmpi-bin libopenmpi-dev
    - name: Installing UCX
      run: wget https://github.com/openucx/ucx/releases/download/v1.13.1/ucx-1.13.1.tar.gz -P $HOME/ucx && (cd $HOME/ucx && tar xzf ucx-1.13.1.tar.gz) && (cd $HOME/ucx/ucx-1.13.1 && ./contrib/configure-release --prefix=$PWD/install --with-go=no && make -j8 install)
    - name: Export Arrow Path
      run: export LD_LIBRARY_PATH=$PWD/build/arrow/install/lib64:$PWD/build/glog/install/lib64:$$PWD/build/lib64:$PWD/build/lib:$LD_LIBRARY_PATH

    - name: Build and test
      run: python3 -m venv ENV && ./build.sh -pyenv $(pwd)/ENV -bpath $(pwd)/build --cpp --test --python --pytest --cmake-flags "-DCYLON_UCX=ON -DUCX_LIBDIR=$HOME/ucx/ucx-1.13.1/install/lib -DUCX_INCLUDEDIR=$HOME/ucx/ucx-1.13.1/install/include -DMPI_C_COMPILER=$(which mpicc) -DMPI_CXX_COMPILER=$(which mpicxx)"
    - name: Build java
      run: ./build.sh -pyenv $(pwd)/ENV -bpath $(pwd)/build --java

